"""Initial

Revision ID: 34ea0cd069cd
Revises: 
Create Date: 2025-08-06 00:38:33.589741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ea0cd069cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order', 'product_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order', 'quantity',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('order', 'order_date',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('order', 'delivery_date',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order', 'status',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('order', 'payment_method',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('order', 'payment_status',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('order', 'shipping_address',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('order', 'tracking_number',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order', 'discount_applied',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('order', 'total_amount',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('order', 'tax_amount',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('order', 'notes',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Text(),
               nullable=True)
    op.drop_constraint(op.f('order_user_id_key'), 'order', type_='unique')
    op.drop_table_comment(
        'order',
        existing_comment='Таблица для учёта заказов',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'order',
        'Таблица для учёта заказов',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint(op.f('order_user_id_key'), 'order', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('order', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('order', 'tax_amount',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('order', 'total_amount',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('order', 'discount_applied',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('order', 'tracking_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('order', 'shipping_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('order', 'payment_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('order', 'payment_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('order', 'status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('order', 'delivery_date',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('order', 'order_date',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('order', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('order', 'product_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('order', 'user_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
